from PyQt5 import QtCore, QtGui
from PyQt5.QtWidgets import QMainWindow, QTextEdit, QCheckBox, QPushButton, QLabel, QMenuBar, QAction, QFileDialog, QRadioButton, QMenu

def Windows():
    ##الخطوط
    labels_font = QtGui.QFont()
    labels_font.setPointSize(9)
    textbox_font = QtGui.QFont()
    textbox_font.setPointSize(12)
    
    #نافذة عني
    Windows.AboutWindow = QMainWindow()
    Windows.AboutWindow.setFixedSize(378, 160)
    Windows.AboutWindow.setWindowTitle("عني")

    Windows.about_textbox = QTextEdit(Windows.AboutWindow)
    Windows.about_textbox.setGeometry(QtCore.QRect(0, 0, 378, 160))
    Windows.about_textbox.setFont(labels_font)
    Windows.about_textbox.setReadOnly(True)
    Windows.about_textbox.setText("طوّرت هذه الأداة من قبل Asgore_Undertale\nصفحتي على github:\nhttps://github.com/asgore-undertale\nلك كامل الحرية في التعديل والنشر،\nبشرط ذكري وصفحتي.")

    #نافذة معلومات مهمة
    Windows.ImportantWindow = QMainWindow()
    Windows.ImportantWindow.setFixedSize(378, 60)
    Windows.ImportantWindow.setWindowTitle("معلومات مهمة")

    Windows.important_textbox = QTextEdit(Windows.ImportantWindow)
    Windows.important_textbox.setGeometry(QtCore.QRect(0, 0, 378, 160))
    Windows.important_textbox.setFont(labels_font)
    Windows.important_textbox.setReadOnly(True)
    Windows.important_textbox.setText("- للكتابة بالبايتات في الحقول الصغيرة اكتب [b] ثم اكتب بعدها بالبايتات.\n  (ولا تضع فراغات)\n- لا تفتح ملفات الاكسل أثناء تشغيل الأداة.")

    #نافذة BMFont_to_FIB
    Windows.BMFont_to_FIB_Window = QMainWindow()
    Windows.BMFont_to_FIB_Window.setFixedSize(275, 120)
    Windows.BMFont_to_FIB_Window.setWindowTitle("نافذة الإدخال")

    Windows.FIB_Table = QTextEdit(Windows.BMFont_to_FIB_Window)
    Windows.FIB_Table.setGeometry(QtCore.QRect(10, 10, 150, 26))
    Windows.FIB_Table_label = QLabel(Windows.BMFont_to_FIB_Window)
    Windows.FIB_Table_label.setGeometry(QtCore.QRect(170, 10, 95, 26))
    Windows.FIB_Table_label.setText("جدول عرض الحروف:")
    Windows.BMFont_File = QTextEdit(Windows.BMFont_to_FIB_Window)
    Windows.BMFont_File.setGeometry(QtCore.QRect(10, 43, 150, 26))
    Windows.BMFont_File_label = QLabel(Windows.BMFont_to_FIB_Window)
    Windows.BMFont_File_label.setGeometry(QtCore.QRect(170, 43, 95, 26))
    Windows.BMFont_File_label.setText("ملف BMFont:")

    Windows.BMFont_Button = QPushButton(Windows.BMFont_to_FIB_Window)
    Windows.BMFont_Button.move(160, 80)
    Windows.BMFont_Button.setText("بدء")

    #نافذة خيارات التحويل
    Windows.OptionsWindow_Width = 400
    checkbox_size = [Windows.OptionsWindow_Width-5, 16]
    textedit_size = [30, 26]
    def pos_y(line_num, Height = checkbox_size[1], Between_every_y = 20):
        y = (Between_every_y+checkbox_size[1]) * line_num + (Between_every_y-Height//2)
        return y

    Windows.OptionsWindow = QMainWindow()
    Windows.OptionsWindow.setFixedSize(Windows.OptionsWindow_Width, 500)
    Windows.OptionsWindow.setWindowTitle("خيارات التحويل")

    Windows.DDL_check = QCheckBox("حذف الأسطر المكررة", Windows.OptionsWindow)
    Windows.DDL_check.setGeometry(QtCore.QRect(0, pos_y(0), checkbox_size[0], checkbox_size[1]))
    Windows.DDL_check.setLayoutDirection(QtCore.Qt.RightToLeft)
    Windows.SSL_check = QCheckBox("ترتيب السطور من الأقصر للأطول", Windows.OptionsWindow)
    Windows.SSL_check.setGeometry(QtCore.QRect(0, pos_y(1), checkbox_size[0], checkbox_size[1]))
    Windows.SSL_check.setLayoutDirection(QtCore.Qt.RightToLeft)
    Windows.SLS_check = QCheckBox("ترتيب السطور من الأطول للأقصر", Windows.OptionsWindow)
    Windows.SLS_check.setGeometry(QtCore.QRect(0, pos_y(2), checkbox_size[0], checkbox_size[1]))
    Windows.SLS_check.setLayoutDirection(QtCore.Qt.RightToLeft)
    Windows.RA_check = QCheckBox("تجميد النص العربي", Windows.OptionsWindow)
    Windows.RA_check.setGeometry(QtCore.QRect(0, pos_y(3), checkbox_size[0], checkbox_size[1]))
    Windows.RA_check.setLayoutDirection(QtCore.Qt.RightToLeft)
    Windows.UA_check = QCheckBox("إلغاء تجميد النص العربي", Windows.OptionsWindow)
    Windows.UA_check.setGeometry(QtCore.QRect(0, pos_y(4), checkbox_size[0], checkbox_size[1]))
    Windows.UA_check.setLayoutDirection(QtCore.Qt.RightToLeft)
    Windows.C_check = QCheckBox("تحويل النص", Windows.OptionsWindow)
    Windows.C_check.setGeometry(QtCore.QRect(0, pos_y(5), checkbox_size[0], checkbox_size[1]))
    Windows.C_check.setLayoutDirection(QtCore.Qt.RightToLeft)
    Windows.UC_check = QCheckBox("إلغاء تحويل النص", Windows.OptionsWindow)
    Windows.UC_check.setGeometry(QtCore.QRect(0, pos_y(6), checkbox_size[0], checkbox_size[1]))
    Windows.UC_check.setLayoutDirection(QtCore.Qt.RightToLeft)
    Windows.RT_check = QCheckBox("عكس النص", Windows.OptionsWindow)
    Windows.RT_check.setGeometry(QtCore.QRect(0, pos_y(7), checkbox_size[0], checkbox_size[1]))
    Windows.RT_check.setLayoutDirection(QtCore.Qt.RightToLeft)
    Windows.RAO_check = QCheckBox("عكس العربية في النص (تجريبي)", Windows.OptionsWindow)
    Windows.RAO_check.setGeometry(QtCore.QRect(0, pos_y(8), checkbox_size[0], checkbox_size[1]))
    Windows.RAO_check.setLayoutDirection(QtCore.Qt.RightToLeft)
    Windows.FIB_check = QCheckBox("ضع النص في مربع", Windows.OptionsWindow)
    Windows.FIB_check.setGeometry(QtCore.QRect(0, pos_y(9), checkbox_size[0], checkbox_size[1]))
    Windows.FIB_check.setLayoutDirection(QtCore.Qt.RightToLeft)
    Windows.Ext_check = QCheckBox("استخرج من النص", Windows.OptionsWindow)
    Windows.Ext_check.setGeometry(QtCore.QRect(0, pos_y(10), checkbox_size[0], checkbox_size[1]))
    Windows.Ext_check.setLayoutDirection(QtCore.Qt.RightToLeft)

    ##
    Windows.UC_database_button = QPushButton(Windows.OptionsWindow)
    Windows.UC_database_button.setGeometry(QtCore.QRect(35, 10, 93, 56))
    Windows.UC_database_button.setText("قاعدة بيانات\nالتحويل")
    Windows.W_database_button = QPushButton(Windows.OptionsWindow)
    Windows.W_database_button.setGeometry(QtCore.QRect(35, 70, 93, 56))
    Windows.W_database_button.setText("قاعدة بيانات\nعرض الحروف")

    Windows.start_command = QTextEdit(Windows.OptionsWindow)
    Windows.start_command.setGeometry(QtCore.QRect(10, 142, 50, 26))
    Windows.start_com_label = QLabel(Windows.OptionsWindow)
    Windows.start_com_label.setGeometry(QtCore.QRect(100, 142, 60, 26))
    Windows.start_com_label.setText("قبل الأوامر:")
    Windows.end_command = QTextEdit(Windows.OptionsWindow)
    Windows.end_command.setGeometry(QtCore.QRect(10, 175, 50, 26))
    Windows.end_com_end_label = QLabel(Windows.OptionsWindow)
    Windows.end_com_end_label.setGeometry(QtCore.QRect(125, 175, 35, 26))
    Windows.end_com_end_label.setText("بعدها:")

    Windows.page_command = QTextEdit(Windows.OptionsWindow)
    Windows.page_command.setGeometry(QtCore.QRect(10, 208, 50, 26))
    Windows.page_com_label = QLabel(Windows.OptionsWindow)
    Windows.page_com_label.setGeometry(QtCore.QRect(65, 208, 95, 26))
    Windows.page_com_label.setText("أمر صفحة جديدة:")
    Windows.line_command = QTextEdit(Windows.OptionsWindow)
    Windows.line_command.setGeometry(QtCore.QRect(10, 241, 50, 26))
    Windows.line_com_label = QLabel(Windows.OptionsWindow)
    Windows.line_com_label.setGeometry(QtCore.QRect(95, 241, 65, 26))
    Windows.line_com_label.setText("سطر جديد:")

    Windows.textzone_width = QTextEdit(Windows.OptionsWindow)
    Windows.textzone_width.setGeometry(QtCore.QRect(10, 274, 50, 26))
    Windows.textzone_width_label = QLabel(Windows.OptionsWindow)
    Windows.textzone_width_label.setGeometry(QtCore.QRect(65, 274, 95, 26))
    Windows.textzone_width_label.setText("عرض المربع (px):")
    Windows.textzone_lines = QTextEdit(Windows.OptionsWindow)
    Windows.textzone_lines.setGeometry(QtCore.QRect(10, 307, 50, 26))
    Windows.textzone_lines_label = QLabel(Windows.OptionsWindow)
    Windows.textzone_lines_label.setGeometry(QtCore.QRect(80, 307, 80, 26))
    Windows.textzone_lines_label.setText("سطور المربع:")

    Windows.Slash_check = QCheckBox(u"\u005c\u006e" + ", " + u"\u005c\u0074" + ", " + u"\u005c\u0072" + ", " + u"\u005c\u0061" + "  :مراعاة", Windows.OptionsWindow)
    Windows.Slash_check.setGeometry(QtCore.QRect(15, 335, 140, 26))
    Windows.Slash_check.setLayoutDirection(QtCore.Qt.RightToLeft)

    Windows.before_text_convert = QTextEdit(Windows.OptionsWindow)
    Windows.before_text_convert.setGeometry(QtCore.QRect(10, 368, 50, 26))
    Windows.before_text_convert_label = QLabel(Windows.OptionsWindow)
    Windows.before_text_convert_label.setGeometry(QtCore.QRect(65, 368, 95, 26))
    Windows.before_text_convert_label.setText("ما قبل النصوص:")
    Windows.after_text_convert = QTextEdit(Windows.OptionsWindow)
    Windows.after_text_convert.setGeometry(QtCore.QRect(10, 401, 50, 26))
    Windows.after_text_convert_label = QLabel(Windows.OptionsWindow)
    Windows.after_text_convert_label.setGeometry(QtCore.QRect(65, 401, 95, 26))
    Windows.after_text_convert_label.setText("ما بعدها:")

    Windows.min_text_convert = QTextEdit(Windows.OptionsWindow)
    Windows.min_text_convert.setGeometry(QtCore.QRect(10, 434, 50, 26))
    Windows.min_text_convert_label = QLabel(Windows.OptionsWindow)
    Windows.min_text_convert_label.setGeometry(QtCore.QRect(65, 434, 95, 26))
    Windows.min_text_convert_label.setText("أقصى حد لقصرها:")
    Windows.max_text_convert = QTextEdit(Windows.OptionsWindow)
    Windows.max_text_convert.setGeometry(QtCore.QRect(10, 467, 50, 26))
    Windows.max_text_convert_label = QLabel(Windows.OptionsWindow)
    Windows.max_text_convert_label.setGeometry(QtCore.QRect(65, 467, 95, 26))
    Windows.max_text_convert_label.setText("أقصى حد لطولها:")
    ##


    #النافذة الرئيسية
    Windows.MainWindow = QMainWindow()
    Windows.MainWindow.setFixedSize(756, 344)
    Windows.MainWindow.setWindowTitle("ATCEE 1.3v")

    Windows.result_text = QTextEdit(Windows.MainWindow)
    Windows.result_text.setGeometry(QtCore.QRect(13, 62, 301, 253))
    Windows.result_text.setFont(textbox_font)
    Windows.entered_text = QTextEdit(Windows.MainWindow)
    Windows.entered_text.setGeometry(QtCore.QRect(440, 66, 301, 253))
    Windows.entered_text.setFont(textbox_font)

    Windows.convert_button = QPushButton(Windows.MainWindow)
    Windows.convert_button.setGeometry(QtCore.QRect(330, 116, 93, 28))
    Windows.convert_button.setText("تحويل")
    Windows.openfile_button = QPushButton(Windows.MainWindow)
    Windows.openfile_button.setGeometry(QtCore.QRect(330, 166, 93, 41))
    Windows.openfile_button.setText("فتح ملف\nنص")

    Windows.label = QLabel(Windows.MainWindow)
    Windows.label.setGeometry(QtCore.QRect(654, 36, 81, 20))
    Windows.label.setFont(labels_font)
    Windows.label.setText("النص الداخل:")
    Windows.label_2 = QLabel(Windows.MainWindow)
    Windows.label_2.setGeometry(QtCore.QRect(220, 36, 81, 20))
    Windows.label_2.setFont(labels_font)
    Windows.label_2.setText("النص الناتج:")

    Windows.menubar = QMenuBar(Windows.MainWindow)
    Windows.menubar.setGeometry(QtCore.QRect(0, 0, 756, 26))
    Windows.menubar.setLayoutDirection(QtCore.Qt.RightToLeft)
    Windows.converting_options = QAction("خيارات التحويل", Windows.MainWindow)
    Windows.entering = QAction("الإدخال والاستخراج", Windows.MainWindow)
    Windows.about = QAction("عني", Windows.MainWindow)
    Windows.important = QAction("؟", Windows.MainWindow)
    Windows.OtherScriptmenu = QMenu("سكربتات أخرى", Windows.menubar)
    Windows.BMFont_to_FIB_Action = QAction("BMFont_to_FIB", Windows.MainWindow)
    Windows.OtherScriptmenu.addAction(Windows.BMFont_to_FIB_Action)


    Windows.menubar.addAction(Windows.converting_options)
    Windows.menubar.addAction(Windows.entering)
    Windows.menubar.addAction(Windows.OtherScriptmenu.menuAction())
    Windows.menubar.addAction(Windows.about)
    Windows.menubar.addAction(Windows.important)

    #نافذة الإدخال
    Windows.EnteringWindow = QMainWindow()
    Windows.EnteringWindow.setFixedSize(756, 363)
    Windows.EnteringWindow.setWindowTitle("نافذة الإدخال")

    Windows.translate_text = QTextEdit(Windows.EnteringWindow)
    Windows.translate_text.setGeometry(QtCore.QRect(13, 34, 301, 140))
    Windows.translate_text.setFont(textbox_font)
    Windows.original_text = QTextEdit(Windows.EnteringWindow)
    Windows.original_text.setGeometry(QtCore.QRect(440, 40, 301, 140))
    Windows.original_text.setFont(textbox_font)

    Windows.label = QLabel(Windows.EnteringWindow)
    Windows.label.setGeometry(QtCore.QRect(654, 10, 81, 20))
    Windows.label.setFont(labels_font)
    Windows.label.setText("النص الأصلي:")
    Windows.label_2 = QLabel(Windows.EnteringWindow)
    Windows.label_2.setGeometry(QtCore.QRect(220, 10, 81, 20))
    Windows.label_2.setFont(labels_font)
    Windows.label_2.setText("الترجمة:")

    Windows.enter_button = QPushButton(Windows.EnteringWindow)
    Windows.enter_button.setGeometry(QtCore.QRect(330, 45, 93, 28))
    Windows.enter_button.setText("إدخال")
    Windows.convert_enter_button = QPushButton(Windows.EnteringWindow)
    Windows.convert_enter_button.setGeometry(QtCore.QRect(330, 80, 93, 41))
    Windows.convert_enter_button.setText("تحويل\nوإدخال")
    Windows.extract_button = QPushButton(Windows.EnteringWindow)
    Windows.extract_button.setGeometry(QtCore.QRect(330, 130, 93, 28))
    Windows.extract_button.setText("استخراج")

    Windows.before_text = QTextEdit(Windows.EnteringWindow)
    Windows.before_text.setGeometry(QtCore.QRect(25, 190, 50, 26))
    Windows.before_text_label = QLabel(Windows.EnteringWindow)
    Windows.before_text_label.setGeometry(QtCore.QRect(70, 190, 60, 26))
    Windows.before_text_label.setText("ما يسبقه:")
    Windows.after_text = QTextEdit(Windows.EnteringWindow)
    Windows.after_text.setGeometry(QtCore.QRect(145, 190, 50, 26))
    Windows.after_text_label = QLabel(Windows.EnteringWindow)
    Windows.after_text_label.setGeometry(QtCore.QRect(215, 190, 160, 26))
    Windows.after_text_label.setText("ما يلحق النص في الملفات:")

    Windows.min_text = QTextEdit(Windows.EnteringWindow)
    Windows.min_text.setGeometry(QtCore.QRect(145, 223, 50, 26))
    Windows.min_text_label = QLabel(Windows.EnteringWindow)
    Windows.min_text_label.setGeometry(QtCore.QRect(175, 223, 200, 26))
    Windows.min_text_label.setText("أقصى حد لقصر النصوص المستخرجة:")
    Windows.max_text = QTextEdit(Windows.EnteringWindow)
    Windows.max_text.setGeometry(QtCore.QRect(25, 223, 50, 26))
    Windows.max_text_label = QLabel(Windows.EnteringWindow)
    Windows.max_text_label.setGeometry(QtCore.QRect(70, 223, 60, 26))
    Windows.max_text_label.setText("وطولها:")

    Windows.database_check = QCheckBox("استخدام قاعدة البيانات", Windows.EnteringWindow)
    Windows.database_check.setGeometry(QtCore.QRect(570, 193, 150, 16))
    Windows.database_check.setLayoutDirection(QtCore.Qt.RightToLeft)
    Windows.too_long_check = QCheckBox("عدم إدخال ترجمات أطول من النص الأصلي (بقيم الهيكس)", Windows.EnteringWindow)
    Windows.too_long_check.setGeometry(QtCore.QRect(440, 218,280, 16))
    Windows.too_long_check.setLayoutDirection(QtCore.Qt.RightToLeft)
    Windows.translation_place_check = QCheckBox(":مكان الترجمة في حال كانت أقصر", Windows.EnteringWindow)
    Windows.translation_place_check.setGeometry(QtCore.QRect(470, 243,250, 16))
    Windows.translation_place_check.setLayoutDirection(QtCore.Qt.RightToLeft)

    Windows.first_radio = QRadioButton(Windows.EnteringWindow)
    Windows.first_radio.setGeometry(QtCore.QRect(580, 268,100, 16))
    Windows.first_radio.setText("أول")
    Windows.first_radio.setLayoutDirection(QtCore.Qt.RightToLeft)
    Windows.middle_radio = QRadioButton(Windows.EnteringWindow)
    Windows.middle_radio.setGeometry(QtCore.QRect(510, 268,100, 16))
    Windows.middle_radio.setText("وسط")
    Windows.middle_radio.setLayoutDirection(QtCore.Qt.RightToLeft)
    Windows.last_radio = QRadioButton(Windows.EnteringWindow)
    Windows.last_radio.setGeometry(QtCore.QRect(440, 268,100, 16))
    Windows.last_radio.setText("آخر")
    Windows.last_radio.setLayoutDirection(QtCore.Qt.RightToLeft)

    Windows.input_from_folder = QPushButton(Windows.EnteringWindow)
    Windows.input_from_folder.setGeometry(QtCore.QRect(610, 300, 93, 41))
    Windows.input_from_folder.setText("المجلد الحاوي\nللملفات")
    Windows.output_from_folder = QPushButton(Windows.EnteringWindow)
    Windows.output_from_folder.setGeometry(QtCore.QRect(500, 300, 93, 41))
    Windows.output_from_folder.setText("مجلد الملفات\nبعد الإدخال")
    Windows.text_database_button = QPushButton(Windows.EnteringWindow)
    Windows.text_database_button.setGeometry(QtCore.QRect(390, 300, 93, 41))
    Windows.text_database_button.setText("فتح قاعدة\nبيانات النصوص")
    Windows.extract_database_button = QPushButton(Windows.EnteringWindow)
    Windows.extract_database_button.setGeometry(QtCore.QRect(280, 300, 93, 41))
    Windows.extract_database_button.setText("فتح قاعدة\nبيانات الاستخراج")
    